name: pytorch-dqn
channels:
- pytorch
- defaults
dependencies:
- python=3.8
- cudatoolkit=11.3
- pytorch=1.12.1
- torchvision=0.13.1
- torchaudio=0.12.1
- idna=3.4
- seaborn=0.12.1
- ipywidgets
- tensorboard
- tensorboardX
- pip
- pip:
  - gym==0.26.0
  - gym-notices==0.0.8
  - kiwisolver==1.4.4
  - Pillow==9.3.0
  - numpy==1.23.5
  - pygame==2.1.0
  - matplotlib==3.6.2
  - tqdm==4.64.1
  - typing_extensions==4.4.0
  - ipykernel
  - gym[Box2D]
  - optuna